# This is the CI Pipeline to be triggered on self-hosted runner
name: CI Pipeline
on:
  push:
    branches:
      -  jfrog-test

env:
  # DOCKER_IMAGE: meeraparigi/petapp:${{ github.sha }}
  MAVEN_OPTS: "-DskipTests=true"

jobs:
  build:
    uses: ./.github/workflows/javabuild.yml
    secrets: inherit

  sonar:
    uses: ./.github/workflows/sonar.yml
    needs: build
    secrets: inherit
    
  jfrog:
    uses: ./.github/workflows/jfrog.yml
    needs: sonar
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    needs: jfrog
    secrets: inherit
    
  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit
