# This is the image push file
name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: java_build
    #env:
      # DOCKER_IMAGE: meeraparigi/petapp:${{ github.sha }}

    steps:
      - name: Build Docker Image
        run: |
          sudo docker build -t ${{ env.DOCKER_IMAGE }}
          sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker_image
          path: docker_image.tar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker Push Image
        run: sudo docker push ${{ env.DOCKER_IMAGE }}
        
        
