# This is the build file
name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build with Maven
        run: |
          mvn clean package -Dskiptests

      - name: Verify Target Directory Exists
        run: |
          if [ ! -d "target" ]; then
            echo "Error: target directory does not exist. Maven build may have failed."
            exit 1
          fi
        
      - name: Upload Build Architect
        uses: actions/upload-artifact@v4.4.1
        with:
          name: jar
          path: target/*.jar
