# This is the build file
name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: java_build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Architect
        uses: actions/upload-artifact@v4.4.1
        with:
          name: jar
          path: target/*.jar

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://trialmeeraparigi.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Upload JAR to JFROG
        run: |
          #sudo jf rt u "target/*.jar" "petfrog-repo"
          sudo jf rt u "target/*.jar" "petfrog-repo/" --url="https://trialmeeraparigi.jfrog.io/artifactory/" --user=${{ secrets.JFROG_USER }} --password=${{ secrets.JFROG_PASSWORD }}R
