# This file contains code to upload an artifact to JFrog
name: JFrog Upload

on:
  push:
    branches:
      - jfrog-test

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install JFrog CLI using Install Script
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        sudo mv ~/.jfrog/bin/jfrog /usr/local/bin/jfrog
        chmod +x /usr/local/bin/jfrog

    - name: Verify JFrog CLI Installation
      run: |
        ls -lah /usr/local/bin/ | grep jfrog || { echo "JFrog CLI binary missing!"; exit 1; }
        which jfrog || { echo "JFrog CLI not found in PATH!"; exit 1; }
        jfrog --version
        
    - name: Configure JFrog CLI using secrets User and Password
      run:  |
        jfrog config add my-jfrog \
            --artifactory-url=${{ secrets.JFROG_URL }}/artifactory \
            --user=${{ secrets.JFROG_USER }} \
            --password=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false

    - name: Authenticate with JFrog (using API Token)
      run: |
        jfrog config edit my-jfrog --access-token=${{ secrets.JFROG_TOKEN }} 

    - name: Upload Artifact to JFrog Artifactory
      run: jfrog rt upload "target/*.jar" "petfrog-repo/*.jar" --build-name=petapp-build --build-number=${{ github.run_number }}

    - name: Publish Build Info
      run: jfrog rt bp petapp-build ${{ github.run_number }}
