# This file contains code to upload an artifact to JFrog
name: JFrog Upload

on:
  push:
    branches:
      - jfrog-test

jobs:
  upload-artifact:
    runs-on: java-build

    steps:
    
    - name: Install JFrog CLI
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/jfrog
        chmod +x /usr/local/bin/jfrog
        echo "JFrog CLI installed successfully."

    - name: Verify JFrog CLI Installation
      run: |
        which jfrog || { echo "JFrog CLI not found in PATH!"; exit 1; }
        jfrog --version
        
    - name: Configure JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4.5.6
      with:
        version: latest
      env:
        JFROG_URL: ${{ secrets.JFROG_URL }}
        JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
       
    - name: Verify JFrog Configuration
      run: |
        jfrog config show my-jfrog-new1

    - name: Upload Artifact to JFrog Artifactory
      run: |
        jfrog rt upload "/target/*.jar" "petfrog-repo/" --build-name=petapp-build --build-number=${{ github.run_number }}

    - name: Publish Build Info
      run: |
        jfrog rt bp petapp-build ${{ github.run_number }}
