# This file contains code to upload an artifact to JFrog
name: JFrog Upload

on:
  push:
    branches:
      - jfrog-test

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
        
    - name: Configure JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4.5.6
      with:
        version: latest
      env:
        JFROG_URL: ${{ secrets.JFROG_URL }}
        JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
       
    - name: Verify JFrog Configuration
      run: |
        jfrog config show my-jfrog-new2

    - name: Upload Artifact to JFrog Artifactory
      run: |
        jfrog rt upload "target/my-artifact.jar" "petfrog-repo/" --build-name=petapp-build --build-number=${{ github.run_number }}

    - name: Publish Build Info
      run: |
        jfrog rt bp petapp-build ${{ github.run_number }}
