# This file contains code to upload an artifact to JFrog
name: JFrog Upload

on:
  push:
    branches:
      - jfrog-test

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install JFrog CLI
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        echo "$HOME/.jfrog/bin" >> $GITHUB_PATH
        echo "JFrog CLI Installed at: $HOME/.jfrog/bin/jfrog"
        ls -lah $HOME/.jfrog/bin/  # Verify JFrog CLI is present

    - name: Manually Add JFrog to Path
      run: |
        export PATH=$HOME/.jfrog/bin:$PATH
        echo "Updated PATH: $PATH"

    - name: Verify JFrog CLI Installation
      run: |
        which jfrog || echo "JFrog CLI not found in PATH"
        jfrog --version
        
    - name: Configure JFrog CLI using secrets User and Password
      run:  |
        jfrog config add my-jfrog \
            --artifactory-url=${{ secrets.JFROG_URL }}/artifactory \
            --user=${{ secrets.JFROG_USER }} \
            --password=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false

    - name: Authenticate with JFrog (using API Token)
      run: |
        jfrog config edit my-jfrog --access-token=${{ secrets.JFROG_TOKEN }} 

    - name: Upload Artifact to JFrog Artifactory
      run: jfrog rt upload "target/*.jar" "petfrog-repo/*.jar" --build-name=petapp-build --build-number=${{ github.run_number }}

    - name: Publish Build Info
      run: jfrog rt bp petapp-build ${{ github.run_number }}
