# This file contains code to upload an artifact to JFrog
name: JFrog Upload

on:
  push:
    branches:
      - jfrog-test

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install JFrog CLI
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        JFROG_PATH=$(find $HOME -type f -name "jfrog" 2>/dev/null | head -n 1)

        if [[ -z "$JFROG_PATH" ]]; then
          echo "Error: JFrog CLI installation failed. Binary not found."
          exit 1
        fi

        sudo mv "$JFROG_PATH" /usr/local/bin/jfrog
        sudo chmod +x /usr/local/bin/jfrog
        echo "JFrog CLI successfully installed."

    - name: Verify JFrog CLI Installation
      run: |
        which jfrog || { echo "JFrog CLI not found in PATH!"; exit 1; }
        jfrog --version
        
    - name: Configure JFrog CLI using secrets User and Password
      run:  |
        jfrog config add my-jfrog \
            --artifactory-url=${{ secrets.JFROG_URL }}/artifactory \
            --user=${{ secrets.JFROG_USER }} \
            --password=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false

    - name: Authenticate with JFrog (using API Token)
      run: |
        jfrog config edit my-jfrog --access-token=${{ secrets.JFROG_TOKEN }} 

    - name: Upload Artifact to JFrog Artifactory
      run: jfrog rt upload "target/*.jar" "petfrog-repo/*.jar" --build-name=petapp-build --build-number=${{ github.run_number }}

    - name: Publish Build Info
      run: jfrog rt bp petapp-build ${{ github.run_number }}
